Fix TS2353 error in employeeApi.ts
The error TS2353 was caused by attempting to assign `karyawan_id` to an object of type `profiles` which does not have that property. To resolve this, the `karyawan_id` property is now assigned conditionally, only when the employee data does not exist in profiles.